defaults: &defaults
  docker:
    - image: cyber4all/circleci-aws:debian

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
          
  package:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: |
            export PACKAGE_VERSION=$(cat package.json | jq -r '.version')
            export PACKAGE_NAME=$(cat package.json | jq -r '.name')
      - run:
          name: Install Packages
          command: npm install --production
      - run:
          name: Build
          command: npm run build
      - run:
          name: Create ZIP
          command: zip -r ${PACKAGE_VERSION}.${PACKAGE_NAME}.zip ./node_modules/* ./bin/* *.md package*.json
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run:
  #         name: Node production
  #         command: npm install --production
      
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - test