# docker:
#   - image: circleci/aws-s3@2.0.0

version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node@4.1.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v1-bin-{{ checksum "package.json" }}
          paths:
            - ./bin
  package:
    docker:
      - image: circleci/node@4.1.0
    steps:
      - checkout
      - run:
          name: Install ZIP
          command: apt install -y zip
      - restore_cache:
          keys:
            - v1-bin-{{ checksum "package.json" }}
      - run:
          name: Set Environment Variables
          command: |
            echo "export PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $BASH_ENV
            echo "export PACKAGE_NAME=$(cat package.json | jq -r '.name')" >> $BASH_ENV
      - run:
          name: Install Packages
          command: npm install --production
      - run:
          name: Create ZIP
          command: |
            echo $PACKAGE_NAME
            echo $PACKAGE_VERSION
            mkdir ./artifacts
            zip -r ./artifacts/${PACKAGE_NAME}.${PACKAGE_VERSION}.zip ./node_modules/* ./bin/* *.md package*.json
      - save_cache:
          key: v1-artifacts-{{ checksum "package.json" }}
          paths:
            - ./artifacts
      - store_artifacts:
          path: ./artifacts
  # deploy:
  #   <<: *aws-defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - v1-artifacts-{{ checksum "package.json" }}
  #     - aws-s3/sync:
  #         from: ./
  #         to: $S3_BUCKET_NAME

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_test
      - package:
          requires:
            - build_test
      # - deploy:
      #     requires:
      #       - package
