defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cyber4all/circleci-aws:debian

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm run test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Node production
          command: npm install --production
      
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - test