jobs:
  build_and_test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  build_test:
    jobs:
      - build_and_test