defaults: &defaults
  docker:
    - image: cyber4all/circleci-aws:debian

version: 2
jobs:
  build_test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: v1-bin-{{ checksum "package.json" }}
          paths:
            - ./bin
  package:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install ZIP
          command: apt install -y zip
      - restore_cache:
          keys:
            - v1-bin-{{ checksum "package.json" }}
      - run:
          name: Set Environment Variables
          command: |
            echo "export PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $BASH_ENV
            echo "export PACKAGE_NAME=$(cat package.json | jq -r '.name')" >> $BASH_ENV
      - run:
          name: Install Packages
          command: npm install --production
      - run:
          name: Create ZIP
          command: |
            echo $PACKAGE_NAME
            echo $PACKAGE_VERSION
            zip -r ${PACKAGE_NAME}.${PACKAGE_VERSION}.zip ./node_modules/* ./bin/* *.md package*.json
      - store_artifacts:
          path: ./${PACKAGE_NAME}.${PACKAGE_VERSION}.zip
          destination: build_artifact.zip
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run:
  #         name: Node production
  #         command: npm install --production
      
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_test
      - package:
          requires:
            - build_test
      # - deploy:
      #     requires:
      #       - test